#!/bin/bash -e
set -e



if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/kde3/kdeglobals 6.0.1 -- "$@"
fi

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 7; then
  update-alternatives --remove desktop-grub /usr/share/images/desktop-base/moreblue-orbit-grub.png
fi

if [ "$1" = "configure" -o "$1" = "abort-upgrade" ]; then
    # Alternatives for the background
    #while read background priority; do
    #    update-alternatives --install \
    #        /usr/share/images/desktop-base/desktop-background \
    #        desktop-background \
    #        /usr/share/images/desktop-base/$background $priority
    #done << EOF
#lines-wallpaper_1280x1024.svg 65
#lines-wallpaper_1600x1200.svg 65
#lines-wallpaper_1920x1080.svg 70
#lines-wallpaper_1920x1200.svg 65
#lines-wallpaper_2560x1080.svg 65
#joy-wallpaper_1600x1200.svg 60
#joy-wallpaper_1280x1024.svg 60
#joy-wallpaper_1920x1080.svg 60
#joy-wallpaper_1920x1200.svg 60
#joy-inksplat-wallpaper_1920x1080.svg 60
#spacefun-wallpaper.svg 50
#spacefun-wallpaper-widescreen.svg  50
#moreblue-orbit-wallpaper.svg 40
#moreblue-orbit-wallpaper-widescreen.svg 40
#EOF

		echo "installing parrot background"
		update-alternatives --install /usr/share/images/desktop-base/desktop-background desktop-background /usr/share/backgrounds/default.jpg 80
		
    	echo "installing parrot desktop-background.xml"
    	update-alternatives --install /usr/share/images/desktop-base/desktop-background.xml desktop-background.xml /usr/share/gnome-background-properties/frozenbox-wallpapers.xml 15
        update-alternatives --install /usr/share/images/desktop-base/desktop-background.xml desktop-background.xml /usr/share/mate-background-properties/frozenbox-wallpapers.xml 20

		echo "installing parrot splash"
		update-alternatives --install /usr/share/images/desktop-base/desktop-splash desktop-splash /etc/lightdm/wallpaper.jpg 60

	echo "installing parrot grub"
        update-alternatives --install /usr/share/images/desktop-base/desktop-grub.png desktop-grub /boot/grub/wallpaper.png 30

    # GRUB background
    if which update-grub2 > /dev/null ; then
        sync
        update-grub2 || true
    fi

    if [ -x /usr/sbin/update-initramfs ]; then
        update-initramfs -u
    fi
fi
